"""KB file monitor — polls filesystem for changes and triggers llm-wiki summarization.

Detects new/changed/deleted files in raw/ and wiki/ directories, then
orchestrates the summarization pipeline to keep wiki pages current.
"""

import asyncio
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path

from src.config import settings
from src.schemas.kb_monitor import MonitorStatus, ProcessAllResult, ProcessResult, WatchedFile
from src.services.kb_summarizer import (
    add_raw_frontmatter,
    append_log,
    finalize_wiki_pages,
    summarize_raw_file,
    update_index,
)

logger = logging.getLogger(__name__)


def _wiki_dir() -> str:
    return settings.wiki_path


class KBMonitor:
    """Polls the knowledge base directory and triggers summarization on changes."""

    def __init__(self) -> None:
        self._running = False
        self._task: asyncio.Task | None = None
        self._file_states: dict[str, tuple[float, int]] = {}  # path -> (mtime, size)
        self._last_check: str | None = None
        self._poll_interval = 30

    # ── public API ──────────────────────────────────────────────────

    @property
    def running(self) -> bool:
        return self._running

    def status(self) -> MonitorStatus:
        return MonitorStatus(
            enabled=True,
            running=self._running,
            watched_files=len(self._file_states),
            last_check=self._last_check,
            poll_interval_seconds=self._poll_interval,
        )

    async def start(self, poll_interval: int = 30) -> None:
        if self._running:
            return
        self._running = True
        self._poll_interval = poll_interval
        self._scan_all()  # initial scan
        self._task = asyncio.create_task(self._loop())
        logger.info("KB monitor started (poll=%ds, %d files watched)",
                     poll_interval, len(self._file_states))

    async def stop(self) -> None:
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None
        logger.info("KB monitor stopped")

    async def process_document(self, filepath: str) -> ProcessResult:
        """Manually trigger processing of a single raw file."""
        fname = os.path.basename(filepath)
        if not os.path.exists(filepath):
            return ProcessResult(file=fname, status="error", message="File not found")

        try:
            add_raw_frontmatter(filepath)
            existing = self._list_wiki_stems()
            pages = await summarize_raw_file(filepath, existing_pages=existing)
            if not pages:
                return ProcessResult(file=fname, status="skipped", message="No pages generated by LLM")

            written = finalize_wiki_pages(pages, filepath)
            update_index(pages)
            append_log("ingest", fname, written)
            return ProcessResult(
                file=fname,
                status="processed",
                wiki_pages_updated=[os.path.basename(w) for w in written],
                message=f"Created/updated {len(written)} wiki pages",
            )
        except Exception as e:
            logger.exception("Failed to process %s", filepath)
            return ProcessResult(file=fname, status="error", message=str(e))

    async def process_all(self) -> ProcessAllResult:
        """Process all raw files in the raw/ directory."""
        raw_dir = os.path.join(_wiki_dir(), "raw")
        if not os.path.isdir(raw_dir):
            return ProcessAllResult(total=0, processed=0, skipped=0, errors=0, results=[])

        md_files = sorted(
            os.path.join(raw_dir, fn)
            for fn in os.listdir(raw_dir)
            if fn.endswith(".md")
        )

        results: list[ProcessResult] = []
        processed = skipped = errors = 0

        for fp in md_files:
            r = await self.process_document(fp)
            results.append(r)
            if r.status == "processed":
                processed += 1
            elif r.status == "error":
                errors += 1
            else:
                skipped += 1

        return ProcessAllResult(
            total=len(md_files),
            processed=processed,
            skipped=skipped,
            errors=errors,
            results=results,
        )

    def watched_files(self) -> list[WatchedFile]:
        """Return current state of all watched files."""
        out = []
        for path, (mtime, size) in self._file_states.items():
            if os.path.exists(path):
                cur_mtime = os.path.getmtime(path)
                cur_size = os.path.getsize(path)
                if cur_mtime != mtime or cur_size != size:
                    status = "changed"
                else:
                    status = "unchanged"
            else:
                status = "deleted"

            out.append(WatchedFile(
                path=os.path.relpath(path, _wiki_dir()),
                status=status,
                last_modified=datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat() if mtime else None,
                size=size,
            ))
        out.sort(key=lambda w: w.path)
        return out

    # ── internals ───────────────────────────────────────────────────

    def _list_wiki_stems(self) -> list[str]:
        wiki_dir = os.path.join(_wiki_dir(), "wiki")
        if not os.path.isdir(wiki_dir):
            return []
        return sorted(
            p.stem for p in Path(wiki_dir).glob("*.md")
        )

    def _scan_all(self) -> None:
        for sub in ("raw", "wiki"):
            d = os.path.join(_wiki_dir(), sub)
            if not os.path.isdir(d):
                continue
            for entry in os.scandir(d):
                if entry.is_file(follow_symlinks=False) and entry.name.endswith(".md"):
                    stat = entry.stat()
                    self._file_states[entry.path] = (stat.st_mtime, stat.st_size)

    def _scan_changes(self) -> list[str]:
        """Return list of changed raw/ file paths."""
        changed = []
        raw_dir = os.path.join(_wiki_dir(), "raw")

        seen = set()

        # Check existing and new files
        for sub in ("raw", "wiki"):
            d = os.path.join(_wiki_dir(), sub)
            if not os.path.isdir(d):
                continue
            for entry in os.scandir(d):
                if not entry.is_file(follow_symlinks=False):
                    continue
                if not entry.name.endswith(".md"):
                    continue
                seen.add(entry.path)
                prev = self._file_states.get(entry.path)
                stat = entry.stat()
                if prev is None:
                    self._file_states[entry.path] = (stat.st_mtime, stat.st_size)
                    if sub == "raw":
                        changed.append(entry.path)
                elif prev[0] != stat.st_mtime or prev[1] != stat.st_size:
                    self._file_states[entry.path] = (stat.st_mtime, stat.st_size)
                    if sub == "raw":
                        changed.append(entry.path)

        # Check for deleted files
        removed = [p for p in self._file_states if p not in seen]
        for p in removed:
            del self._file_states[p]

        return changed

    async def _loop(self) -> None:
        while self._running:
            try:
                changed = self._scan_changes()
                self._last_check = datetime.now(timezone.utc).isoformat()
                for fp in changed:
                    logger.info("KB change detected: %s", fp)
                    result = await self.process_document(fp)
                    logger.info("KB process result: %s — %s", result.file, result.status)
            except Exception:
                logger.exception("KB monitor loop error")
            await asyncio.sleep(self._poll_interval)


# Singleton
kb_monitor = KBMonitor()
