"""add_datasource_table_mapping

Revision ID: 00e292349692
Revises: fde7ca1780f1
Create Date: 2026-04-30 11:40:06.130204

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e292349692'
down_revision: str | None = 'fde7ca1780f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS datasources (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name VARCHAR(256) NOT NULL,
            description VARCHAR(1024),
            source_type VARCHAR(32) NOT NULL,
            is_enabled BOOLEAN DEFAULT TRUE,
            config JSONB DEFAULT '{}'::jsonb,
            normalization_rules JSONB DEFAULT '{}'::jsonb,
            last_ingested_at TIMESTAMPTZ,
            total_ingested INTEGER DEFAULT 0,
            status VARCHAR(16) DEFAULT 'active',
            error_message VARCHAR(1024),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.alter_column('agents', 'viewable_roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('agents', 'editable_roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.add_column('datasources', sa.Column('table_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasources', 'table_mapping')
    op.alter_column('agents', 'editable_roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('agents', 'viewable_roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###
