"""add report_type and date_range to reports

Revision ID: 0d5bb1cbc6a7
Revises: fb813315629
Create Date: 2026-05-04 16:37:33.131466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5bb1cbc6a7'
down_revision: Union[str, None] = 'fb813315629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS reports (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            session_id UUID REFERENCES sessions(id) ON DELETE SET NULL,
            user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            space_id UUID REFERENCES spaces(id) ON DELETE SET NULL,
            title VARCHAR(500) NOT NULL DEFAULT 'Untitled Report',
            description TEXT,
            html_content TEXT NOT NULL,
            theme VARCHAR(50) NOT NULL DEFAULT 'ink',
            status VARCHAR(20) NOT NULL DEFAULT 'draft',
            is_public BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.add_column('reports', sa.Column('report_type', sa.String(length=20), server_default='general', nullable=False))
    op.add_column('reports', sa.Column('date_range_start', sa.String(length=10), nullable=True))
    op.add_column('reports', sa.Column('date_range_end', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'date_range_end')
    op.drop_column('reports', 'date_range_start')
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###
