"""add model_type to model_providers

Revision ID: 15cddc4a3f2a
Revises: 012_spaces
Create Date: 2026-04-30 10:07:13.416809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cddc4a3f2a'
down_revision: Union[str, None] = '012_spaces'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_providers', sa.Column('model_type', sa.String(length=16), server_default='llm', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_providers', 'model_type')
    # ### end Alembic commands ###
