"""add model_provider_id to sessions

Revision ID: 3976477caf48
Revises: 15cddc4a3f2a
Create Date: 2026-04-30 10:15:51.447422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3976477caf48'
down_revision: Union[str, None] = '15cddc4a3f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('model_provider_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'model_providers', ['model_provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'model_provider_id')
    # ### end Alembic commands ###
