"""add cron timeout retries

Revision ID: 3f7d4a87e74a
Revises: d0c76689e71f
Create Date: 2026-04-30 12:00:52.364973

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f7d4a87e74a'
down_revision: str | None = 'd0c76689e71f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS cron_jobs (
            id VARCHAR PRIMARY KEY,
            name VARCHAR NOT NULL,
            prompt TEXT NOT NULL,
            schedule VARCHAR NOT NULL,
            timezone_str VARCHAR DEFAULT 'Asia/Shanghai',
            skills JSONB DEFAULT '[]'::jsonb,
            enabled_toolsets JSONB DEFAULT '[]'::jsonb,
            delivery JSONB,
            enabled BOOLEAN DEFAULT TRUE,
            last_run TIMESTAMPTZ,
            next_run TIMESTAMPTZ,
            last_output TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.add_column('cron_jobs', sa.Column('timeout_seconds', sa.String(), nullable=True))
    op.add_column('cron_jobs', sa.Column('max_retries', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_jobs', 'max_retries')
    op.drop_column('cron_jobs', 'timeout_seconds')
    # ### end Alembic commands ###
