"""add cron timeout retries

Revision ID: 3f7d4a87e74a
Revises: d0c76689e71f
Create Date: 2026-04-30 12:00:52.364973

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f7d4a87e74a'
down_revision: str | None = 'd0c76689e71f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_jobs', sa.Column('timeout_seconds', sa.String(), nullable=True))
    op.add_column('cron_jobs', sa.Column('max_retries', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_jobs', 'max_retries')
    op.drop_column('cron_jobs', 'timeout_seconds')
    # ### end Alembic commands ###
