"""add_user_profile_and_invitations

Revision ID: 48a569adf4e6
Revises: d539a71216d9
Create Date: 2026-04-30 15:53:06.305000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a569adf4e6'
down_revision: Union[str, None] = 'd539a71216d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('users', sa.Column('display_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('source', sa.String(length=16), server_default='local', nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    op.add_column('users', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'approved_by')
    op.drop_column('users', 'status')
    op.drop_column('users', 'source')
    op.drop_column('users', 'title')
    op.drop_column('users', 'department')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'display_name')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
