"""add workflow_contexts

Revision ID: 5fbfaf863285
Revises: 3f7d4a87e74a
Create Date: 2026-04-30 13:08:07.846978

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fbfaf863285'
down_revision: str | None = '3f7d4a87e74a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_contexts')
    # ### end Alembic commands ###
