"""add_space_id_to_agents

Revision ID: 61432a83b688
Revises: 7268beefe5b5
Create Date: 2026-04-30 23:43:33.728218

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61432a83b688'
down_revision: str | None = '7268beefe5b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('space_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'space_id')
    # ### end Alembic commands ###
