"""add folder_path to session_files

Revision ID: 6325af2d08a1
Revises: f6aa826b2a89
Create Date: 2026-05-02 16:40:38.611453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6325af2d08a1'
down_revision: Union[str, None] = 'f6aa826b2a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_files', sa.Column('folder_path', sa.String(length=512), server_default='/', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_files', 'folder_path')
    # ### end Alembic commands ###
