"""add_is_builtin_to_agents_and_tools

Revision ID: 716efe2f0c86
Revises: 61432a83b688
Create Date: 2026-05-01 07:36:53.798596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716efe2f0c86'
down_revision: Union[str, None] = '61432a83b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('agents', sa.Column('is_builtin', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('tools', sa.Column('is_builtin', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.execute(sa.text("UPDATE agents SET is_builtin = false WHERE is_builtin IS NULL"))
    op.execute(sa.text("UPDATE tools SET is_builtin = false WHERE is_builtin IS NULL"))
    op.alter_column('agents', 'is_builtin', nullable=False, server_default=None)
    op.alter_column('tools', 'is_builtin', nullable=False, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'is_builtin')
    op.drop_column('agents', 'is_builtin')
    # ### end Alembic commands ###
