"""add confidence to tasks

Revision ID: 7268beefe5b5
Revises: 48a569adf4e6
Create Date: 2026-04-30 17:25:37.364322

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7268beefe5b5'
down_revision: str | None = '48a569adf4e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'confidence')
    # ### end Alembic commands ###
