"""add space_id to agent_memories

Revision ID: c2a0e4a72cbc
Revises: 716efe2f0c86
Create Date: 2026-05-01 20:04:00.044479

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2a0e4a72cbc'
down_revision: str | None = '716efe2f0c86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memories', sa.Column('space_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agent_memories', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_memories', type_='foreignkey')
    op.drop_column('agent_memories', 'space_id')
    # ### end Alembic commands ###
