"""add space_id to mcp_servers

Revision ID: d539a71216d9
Revises: 5fbfaf863285
Create Date: 2026-04-30 13:34:00.611983

Idempotency note (deploy fix):
    This migration runs before ``012_spaces``'s space_id fan-out loop, so
    on a fresh DB it normally adds the column itself. However, some old
    deployments went through ``012_spaces`` first (or custom bootstrap
    created the column), in which case this autogenerated migration
    would fail with ``column "space_id" of relation "mcp_servers" already
    exists``. Guards below keep the migration safe regardless of which
    order columns appeared.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd539a71216d9'
down_revision: str | None = '5fbfaf863285'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_TABLE = "mcp_servers"
_COLUMN = "space_id"
_FK_NAME = "fk_mcp_servers_space_id"


def _has_column(insp, table: str, column: str) -> bool:
    return column in {c["name"] for c in insp.get_columns(table)}


def _space_fk(insp, table: str) -> dict | None:
    for fk in insp.get_foreign_keys(table):
        if (
            _COLUMN in (fk.get("constrained_columns") or [])
            and fk.get("referred_table") == "spaces"
        ):
            return fk
    return None


def upgrade() -> None:
    insp = sa.inspect(op.get_bind())
    if not _has_column(insp, _TABLE, _COLUMN):
        op.add_column(_TABLE, sa.Column(_COLUMN, sa.UUID(), nullable=True))
    insp = sa.inspect(op.get_bind())
    if _space_fk(insp, _TABLE) is None:
        op.create_foreign_key(
            _FK_NAME, _TABLE, "spaces",
            [_COLUMN], ["id"], ondelete="SET NULL",
        )


def downgrade() -> None:
    insp = sa.inspect(op.get_bind())
    fk = _space_fk(insp, _TABLE)
    if fk is not None:
        op.drop_constraint(fk["name"] or _FK_NAME, _TABLE, type_="foreignkey")
    insp = sa.inspect(op.get_bind())
    if _has_column(insp, _TABLE, _COLUMN):
        op.drop_column(_TABLE, _COLUMN)
