"""add space_id to mcp_servers

Revision ID: d539a71216d9
Revises: 5fbfaf863285
Create Date: 2026-04-30 13:34:00.611983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd539a71216d9'
down_revision: Union[str, None] = '5fbfaf863285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('space_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mcp_servers', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.drop_column('mcp_servers', 'space_id')
    # ### end Alembic commands ###
