import type { ThemeConfig } from 'antd';

// ── Shared tokens ──────────────────────────────────────────────────────────
const shared = {
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  fontSize: 14,
  fontSizeLG: 15,
  fontSizeSM: 13,
  lineHeight: 1.6,
  controlHeight: 36,
  controlHeightLG: 44,
  borderRadius: 8,
  borderRadiusLG: 12,
  borderRadiusSM: 6,
} as const;

// ── Dark Theme ─────────────────────────────────────────────────────────────
export const darkTheme: ThemeConfig = {
  token: {
    ...shared,
    colorBgBase: '#0F172A',
    colorBgContainer: '#1E293B',
    colorBgElevated: '#1E293B',
    colorPrimary: '#3B82F6',
    colorSuccess: '#22C55E',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#3B82F6',
    colorText: '#F1F5F9',
    colorTextSecondary: '#94A3B8',
    colorTextTertiary: '#64748B',
    colorBorder: '#334155',
    colorBorderSecondary: '#1E293B',
  },
  components: {
    Layout: {
      bodyBg: '#0F172A',
      headerBg: '#1E293B',
      siderBg: '#1E293B',
      triggerBg: '#334155',
    },
    Button: { fontWeight: 500, primaryShadow: 'none' },
    Input: {
      activeBorderColor: '#3B82F6',
      hoverBorderColor: '#64748B',
      colorBgContainer: '#1E293B',
    },
    Menu: {
      darkItemBg: 'transparent',
      darkItemColor: '#94A3B8',
      darkItemSelectedBg: 'rgba(59,130,246,0.12)',
      darkItemSelectedColor: '#3B82F6',
      darkItemHoverBg: 'rgba(148,163,184,0.06)',
      itemBorderRadius: 6,
      itemMarginInline: 8,
      itemHeight: 38,
      iconSize: 18,
    },
    Card: { colorBgContainer: '#1E293B', paddingLG: 20 },
    Table: {
      headerBg: '#334155',
      headerColor: '#94A3B8',
      rowHoverBg: 'rgba(148,163,184,0.04)',
      borderColor: '#334155',
    },
    Modal: { colorBgElevated: '#1E293B' },
    Tooltip: { colorBgElevated: '#1E293B' },
    Tag: { borderRadiusSM: 4 },
  },
};

// ── Light Theme — AI chat platform inspired ────────────────────────────────
export const lightTheme: ThemeConfig = {
  token: {
    ...shared,
    colorBgBase: '#F9FAFB',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorPrimary: '#2563EB',
    colorSuccess: '#059669',
    colorWarning: '#D97706',
    colorError: '#DC2626',
    colorInfo: '#2563EB',
    colorText: '#111827',
    colorTextSecondary: '#6B7280',
    colorTextTertiary: '#9CA3AF',
    colorBorder: '#E5E7EB',
    colorBorderSecondary: '#F3F4F6',
    colorBgLayout: '#F9FAFB',
    colorBgSpotlight: '#111827',
    colorBgMask: 'rgba(0,0,0,0.45)',
  },
  components: {
    Layout: {
      bodyBg: '#F9FAFB',
      headerBg: '#FFFFFF',
      siderBg: '#FFFFFF',
      triggerBg: '#F3F4F6',
      headerHeight: 56,
    },
    Button: {
      fontWeight: 500,
      primaryShadow: '0 1px 2px rgba(0,0,0,0.05)',
      controlHeight: 36,
      controlHeightLG: 44,
      borderRadius: 8,
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      activeBorderColor: '#2563EB',
      hoverBorderColor: '#9CA3AF',
      borderRadius: 8,
      controlHeight: 40,
    },
    Select: {
      colorBgContainer: '#FFFFFF',
      activeBorderColor: '#2563EB',
      hoverBorderColor: '#9CA3AF',
      borderRadius: 8,
      controlHeight: 40,
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#6B7280',
      itemSelectedBg: 'rgba(37,99,235,0.08)',
      itemSelectedColor: '#2563EB',
      itemHoverBg: 'rgba(0,0,0,0.04)',
      itemBorderRadius: 6,
      itemMarginInline: 8,
      itemHeight: 38,
      iconSize: 18,
      subMenuItemBg: 'transparent',
    },
    Card: {
      colorBgContainer: '#FFFFFF',
      paddingLG: 24,
      borderRadiusLG: 12,
    },
    Table: {
      headerBg: '#F9FAFB',
      headerColor: '#6B7280',
      rowHoverBg: 'rgba(0,0,0,0.02)',
      borderColor: '#E5E7EB',
      borderRadius: 8,
    },
    Modal: {
      borderRadiusLG: 12,
      colorBgElevated: '#FFFFFF',
    },
    Tooltip: { colorBgElevated: '#1F2937' },
    Tag: { borderRadiusSM: 4 },
    Dropdown: { borderRadius: 8, colorBgElevated: '#FFFFFF' },
    Drawer: { borderRadiusLG: 12, colorBgElevated: '#FFFFFF' },
    Segmented: { borderRadius: 8 },
    Tabs: { cardBg: '#F9FAFB', inkBarColor: '#2563EB' },
    Switch: { trackHeight: 24 },
  },
};
